### ISSUE TITLE
[Feature Request] Add a min/max join timer between joining each giveaway.

### ISSUE THREAD

**Issue by JourneyOver** [ShyPixie/steam-tools#3]
So with the recent suspensions/bans that have just started on SteamGifts I am suggesting to add a min/max timer between joining each giveaway entry to lessen the extent of possibly getting suspended/banned.

so for example it hits the min/max timer for it to start joining giveaways again but with the added feature it'll join one giveaway and then wait a certain amount of seconds (somewhere between the min/max) before going on joining another giveaway and keeps on repeating this process always jumping between different seconds per giveaway.

so in total we will have the min/max between each session of it finding giveaways and joining them, and then a min/max between joining each actual giveaway so its at least a bit harder to get caught and end up with a suspension/ban.

**Comment by calendulish** [comment]
But it already works that way by default. You can also set a custom min/max timer in the configuration file for [steamgifts-join](https://github.com/ShyPixie/steam-tools/wiki/steamgifts-join)

**Comment by JourneyOver** [comment]
I'm not talking about the time between it searching for giveaways (which that one is only good if its high so you can actually have some points saved up to join giveaways), I'm talking about when it is actually joining giveaways so it doesn't join all giveaways at once but instead for example a min/max time of 3 to 15 seconds it'll join one giveaway and then wait say like 5 seconds to join the next one and then lets say 9 seconds to join the next and then 13 seconds to join the one after that. 

if we use the current min/max to do what I'm suggesting it'll be hard to even collect up points for the higher point giveaways as it'll always be joining giveaways that are of few points.

I'm not really all that great at explaining this it seems but hopefully this will be a bit more helpful on what I'm trying to request. >..<

**Comment by calendulish** [comment]
Done 4c80e42
Wait the next release

**Comment by JourneyOver** [comment]
Will we be able to control it by our own min/max timers (was part of the suggestion (would have to go by a different name in the config of course) )? because from looking at the code it doesn't look like that's the case. 

but of course either way thanks, as it'll help out a bit with not getting hit by a suspension.

**Comment by calendulish** [comment]
It was a valid suggestion, but I see no need to control it. You can not use anything below 5 seconds, and it's also useless to use anything above 20 seconds, this will not give more "protection".
