### ISSUE TITLE
[steamcompanion-join] Error if i have more than 10 chrome profiles

### ISSUE THREAD

**Issue by titoncio** [ShyPixie/steam-tools#4]
![bugsc-join](https://cloud.githubusercontent.com/assets/6389868/15445589/e4b98850-1ed7-11e6-9f67-38d83ff72413.png)

But works without problem if i manually set the config OR if the program does itself when i have the maximum of 10 profiles.

Also, thanks for this all!

**Comment by calendulish** [comment]
Fixed. Wait the next release.
