### ISSUE TITLE
They changed something, it doesn't work anymore...

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [ShyPixie/steam-tools#5]
Steam Tools v0.8.3
 --> Initializing...
Traceback (most recent call last):
  File "steamgifts-join.py", line 129, in <module>
  File "steamgifts-join.py", line 71, in getGiveaways
AttributeError: 'NoneType' object has no attribute 'extract'

**Comment by Ranthrall** [comment]
Hi,

Please verify:
https://github.com/ShyPixie/steam-tools/wiki/steamgifts-join
In "DeveloperGiveaways" set to "False" an try again.

Configuration file location depends on your system (Linux, Windows, etc).
Linux: ~/.config/steam-tools/
Windows: %LOCALAPPDATA%\steam-tools\

IF WORKS, please LET ME KNOW.
Tks :+1:

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Hi,

thanks for the Answer and Info...

I added that Option and set it to False - It works if set to False - but it also worked for Months without before, so they changed something for Developer Giveaways or why do that happen?

Thanks again!

**Comment by Ranthrall** [comment]
Developer Giveways recently aren't always available on Steamgifts and we don't foressee this.
This will be fixed soon, the leading developer (@ShyPixie) are working on an enhanced GUI version, I'll tell her about this.

![image](https://cloud.githubusercontent.com/assets/5482388/17789584/3d727aba-6569-11e6-9b94-ee0a2ac9755a.png)

**Comment by calendulish** [comment]
This is fixed by 6cc7223

Now you can re-enable the DeveloperGiveaways with the [new release 0.8.4](https://github.com/ShyPixie/steam-tools/releases/tag/v0.8.4)
