### ISSUE TITLE
Steam-Gift Join doesnt work anymore on v0.8.4 and 2.00 GUI

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [ShyPixie/steam-tools#6]
The CLI Version of v0.8.4 only shows 'connecting to Server' and the 2.00 GUI says 'expired' on all and skips all...

I'm online with Chrome and Steamgifts up and running fine, so they changed something in the last Days which caused both to fail now...

**Comment by calendulish** [comment]
Fixed in [v2.0.1](https://github.com/ShyPixie/steam-tools/releases/tag/2.0.1-alpha)
