### ISSUE TITLE
command line start broken

### ISSUE THREAD

**Issue by SuperSandro2000** [ShyPixie/steam-tools#8]
I tried to start steamgifts join via the command line and it does not work.
Here is my console output.
`C:\Tools\Steam Tools>steam-tools.exe -c steamgifts-join
Steam Tools version 2.0.1 WIN64
Copyright (C) 2016 Lara Maia - <dev@lara.click>

 --> Please, check the command line.
 --> The module steamgifts-join don't exist

 --> Exiting...`

**Comment by calendulish** [comment]
The correct module is steamgifts_join, not steamgifts-join.

**Comment by SuperSandro2000** [comment]
thanks
